language: objective-c

xcode_project: RomeKit.xcodeproj
xcode_scheme: RomeKit
osx_image: xcode9
xcode_sdk: macosx10.12

before_install:
  - brew update
  - brew install mongodb

script:
  - mongod --fork --config /usr/local/etc/mongod.conf
  - ./Tests/RomeKitTests/CI/install.sh
  - swift build
  - swift test
